### ISSUE TITLE
level_command put in config not entered into server

### ISSUE THREAD

**Issue by alandball** [AdVetter/XXLDDRace#11]
I put the level commands for privileges I want for moderators or sub admins, into config. But on server logged in as moderator or subadmin those cant be done. A look at the level command status shows it not being changed

eg level_command ban 2
must give ban priv to all levels down to moderator. But its still its default when I look on server as admin. This is same for any level_command I put in config

**Comment by AdVetter** [comment]
You are right, ban is not working for other levels, but the other commands I've tested are working well.

**Comment by alandball** [comment]
You are right. So some level_command in server config adds to moder status but some don't. Like the ban

**Comment by alandball** [comment]
This issue has more to do with bans, is my best guess. Bans added in the config aren't added to server when server starts..
This might be another bug though, and not part of this bug.

**Comment by AdVetter** [comment]
Seems to be a vanilla and/or DDrace issue

vanilla: teeworlds/teeworlds#942
DDRace: GreYFoX/teeworlds#158

**Comment by disarmer** [comment]
it's seems fixed
https://github.com/teeworlds/teeworlds/commit/9fee99b2f6429b7049fc078ddcdeae5e4c74a60b#diff-0

**Comment by AdVetter** [comment]
You are right, thank you :-)
So it will be fixed in the next XXLDDRace version too.
Commit: 9fee99b2f6429b7049fc078ddcdeae5e4c74a60b

**Comment by alandball** [comment]
Yes, its fixed in teeworlds, sorry, I closed in ddrace, but forgot to do so here. Thanks
