### ISSUE TITLE
/login command

### ISSUE THREAD

**Issue by alandball** [AdVetter/XXLDDRace#13]
For xxlddrace there is register and login features. If an admin does this he gets set to correct "level" as well. If then leave server and go back, you are logged out in console and as member.

problem 1: You then use /login password and you get your level in rcon. But sometimes it will be a level lower than you were initially assigned. This can be fixed by logout inside rcon and login to rcon.

If you are not first logged into rcon and use /login, you get your level and is logged into rcon. But no commands will show when press tab. This can be useful for admins if commands show as bind say with login detail to get rcon access quick

If I sound a bit unclear with all the login and whether its rcon or member related, say and I will explain more on irc? Thanks

**Comment by AdVetter** [comment]
The second part is fixed now 2835f7528b1d74f09ccbbb657fa4cdee12322618

but I can't reproduce the Problem 1.

**Comment by alandball** [comment]
I will test this problem 1 when I get home, and if fixed will close. :)

**Comment by alandball** [comment]
cannot reproduce problem 1. So issues are fixed.
