### ISSUE TITLE
available console commands duplicated when logout and login again

### ISSUE THREAD

**Issue by alandball** [AdVetter/XXLDDRace#14]
Everytime logout and login when press tab to see commands, it then shows +1 duplicate of each command.

**Comment by AdVetter** [comment]
Already fixed de3e94d9019ac9004e622a6e87535f51017fec46

This is a client problem, and it was not fixed when Teeworlds 0.6.1 was released.
If you compile the client by yourself, based on the latest sources,  the problem should not occur.
