### ISSUE TITLE
lasers can continue to grab a Mid-air pause

### ISSUE THREAD

**Issue by Dizern** [AdVetter/XXLDDRace#16]
this allows some cheats , for example When you have a drag down dummy to go up a long 1 tile space with a pull laser, pausing in mid-air while being held by the laser, and unpausing, makes you shoot straight up and be able to bypass it.

**Comment by disarmer** [comment]
yes, i can confirm it too

**Comment by AdVetter** [comment]
I don't get how to reproduce this bug. ( But it seems to be a DDRace bug )

**Comment by Dizern** [comment]
it's a pretty big bug and breaks a lot of maps making them too easy

demo here: http://www.mediafire.com/?ebrz7cuka52ot4b
