### ISSUE TITLE
/r bug spam cheat

### ISSUE THREAD

**Issue by Dizern** [AdVetter/XXLDDRace#17]
you can get through several freeze tiles to the other side by holding move and /r down, the program seems to get confused about whether you are freezed or not and you wake up on the other side, i can attach multiple demos if you'd like.

**Comment by AdVetter** [comment]
I can't reproduce this bug, so please attach a demo file.

**Comment by Dizern** [comment]
Okay! here : http://www.mediafire.com/?q10ntxc0kmh2ghs 

this bug produces an immense amount of shortcuts

**Comment by AdVetter** [comment]
Thank you,
I will try to fix it when I have time.

**Comment by disarmer** [comment]
there are patch by player "z", it fixes problem;
http://disarmer.ru/tee/~/z/patches/rddracesolor.diff

``` diff
diff --git a/src/game/server/ddracechat.cpp b/src/game/server/ddracechat.cpp
index 94da03f..f942552 100644
--- a/src/game/server/ddracechat.cpp
+++ b/src/game/server/ddracechat.cpp
@@ -875,7 +875,7 @@ void CGameContext::ConRescue(IConsole::IResult *pResult, void *pUserData)
    {
        if (!pChr->m_LastRescue){

-           float RescueDelay = 1.25;
+           float RescueDelay = 0.25;
            if (pChr->m_FreezeTime == 0)
                pSelf->SendChatTarget(pResult->m_ClientID, "You are not freezed!");
            else if (pChr->m_DeepFreeze)
@@ -919,6 +919,8 @@ void CGameContext::ConRescue(IConsole::IResult *pResult, void *pUserData)
        {
            if (pChr->m_TileIndex != TILE_FREEZE && pChr->m_TileFIndex != TILE_FREEZE)
                pChr->UnFreeze();
+            else
+                pChr->m_LastRescue = 0;
        }
    }
    else
@@ -1071,3 +1073,43 @@ void CGameContext::ConLogOut(IConsole::IResult *pResult, void *pUserData)
    }
 }
```

// Edit XXLTomate: Syntax highlighting

**Comment by AdVetter** [comment]
Thank you, I will test it soon.

**Comment by theanomaly18** [comment]
Tested the patched file with the else statement. Works fine, fixes cheat.

**Comment by AdVetter** [comment]
Thank you, it will be added in the 0.7 release (XXLDDRace 2.0)
