### ISSUE TITLE
player interaction variables not reset with map load

### ISSUE THREAD

**Issue by Dizern** [AdVetter/XXLDDRace#18]
when a map has an entity saying no player interaction (player_hooking 0, player_collision 0),  on a new map load those settings are kept, and not reset, so that maps not intended to be solo still are now in this kind of solo mode.

**Comment by disarmer** [comment]
did you try add this lines to config?

sv_tune_reset 1
sv_ddrace_tune_reset 1

**Comment by Dizern** [comment]
ah i'm sorry i didn't know about it!
