### ISSUE TITLE
incorporating new ddrace fast map download

### ISSUE THREAD

**Issue by Dizern** [AdVetter/XXLDDRace#22]
Latest ddrace servers are downloading maps super fast, xxl needs to have this.

**Comment by AdVetter** [comment]
The latest sources already contain the fast download patch:
https://github.com/XXLTomate/XXLDDRace/commit/cae8c68d8782dfd31017c12915065a68c72729cc

But the binarys on http://XXL-Clan.com are not up to date.

I will recompile them in the next 2 months.
