### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by o-be-one** [AdVetter/XXLDDRace#26]
Hi,

i've compiled latest sources of XXLDDrace64. My servers works good but today, i dont know why, i have a segmentation fault on start for only one server (server on blmapV3). If i run the other bin (1.9 precompiled bin on your forum) XXLDDrace64-server64, it works.

I dont know why day to tomorrow server wont work Oo ?

**Comment by AdVetter** [comment]
If you've compiled the server an the same machine where you are running it, everything _should_ work.
The binaries at the [forum](http://www.xxl-clan.com/showthread.php?tid=17) are at version [2.0](https://github.com/XXLTomate/XXLDDRace/commit/1a2adc18cec36ec6bdd5e7ed574fb9bd464cd00a) now, so you could try them too, but this will not fix your problem long-term.

What os/version are running on your machine?
Does DDRace or the Teeworlds server start correctly?

**Comment by o-be-one** [comment]
Thank you for your support, XXLTomate.

I'll try 2.0 bin on your forum, thanks for the information.

I compile on the same machine where my servers run, using bam (compilation document on official TeeWorlds website).
I'm running Linux Debian 6.0.
No problem with DDWar (last git source) and TeeWorlds (last bin on their website).

I need your latest sources cause i was the aim of some lamers who like to crash my servers :( ...

**Comment by o-be-one** [comment]
Tested with you last 2.0 precompiled bin, works with xxlddrace_server64 but doenst work with xxlddrace64_server64 (i need to host 32 players :s).
