### ISSUE TITLE
Level 4 in memberlist

### ISSUE THREAD

**Issue by AdVetter** [AdVetter/XXLDDRace#29]
If someone is level 4 in memberlist it will be reset to lvl 3 in some cases.

http://www.xxl-clan.com/showthread.php?tid=208

**Comment by alandball** [comment]
Issue https://github.com/XXLTomate/XXLDDRace/issues/13
Problem 1 I mentioned in issue 13 is same as this issue 29, as you end up with 1 level lower than should be. I just explained bad, my apologies
Did not know this problem was still around

**Comment by o-be-one** [comment]
I have this issue but with rcon no problem.
