### ISSUE TITLE
Issue with rules ...

### ISSUE THREAD

**Issue by o-be-one** [AdVetter/XXLDDRace#34]
Hi XXLTomate,

there is an issue with /rules.

I'm running Debian 6 x64 with compiled XXLDDrace x64 64p mod.

Bug :
When a player type /rules, there is the default rules + rules set by sv_rules_line1 (2, 3, ...). So in one of my blocks server, i have a "no blocking" default rule with "block !" personnalised rule ... :(

Thank you ^^ !

**Comment by gs93** [comment]
Have you tried to set `sv_ddrace_rules` to 0?

**Comment by o-be-one** [comment]
Oh gs93 thank you very much, that's it ! sv_ddrace_rules 0 works :).
Thanks a lot again !

Have a nice day ^^.
