### ISSUE TITLE
Anti-Swearing Plugin

### ISSUE THREAD

**Issue by Rhawk** [AdVetter/XXLDDRace#5]
Hello Tomate... I would like if you could maybe help me with something... My in-game name is Furious. I play on Wage Teeworlds servers and I was wondering if you could help me develope a plugin ... What this plugin basicly will do is that it takes the user input from "say" and if the word is e.g. fuck, that it would print it out as $*#^ or &#^$ or whatever... So that if the user wrote:"I fucking hate this map" that it would rather print out:"I &%#&ing hate this map".... I would really like if we can work on this together... I would prefer if it was a plugin made only for Wage...
If you want to talk about it further you can add me on skype or xfire or AIM.
Skype username: rhawk363
Xfire username: rhawk1
AIM username: rhawkie2011

P.S. Sorry that I posted this here. I could not message you because you didn't provide an e-mail.
Thank you for your support
Rhawk

**Comment by AdVetter** [comment]
How should the swearwords be detected? (by a wordlist?)
Generaly I dislike consoring, there is a kick function to kick people swearing around.

**Comment by Rhawk** [comment]
I generally though to add something to the code like:(I am not that good in
C++)

char swearFirst = 'fuck';
char swearFirstFix = '*@&#';

if(PlayerChatLine == 'fuck')
    swap(swearFirst, SwearFirstFix);

Then adding a whole line of swearing words etc.
If you could maybe give me a code to something like this, I would really
appreciate it...
Thank you

On Wed, Dec 28, 2011 at 3:18 AM, XXLTomate <
reply@reply.github.com

**Comment by disarmer** [comment]
we can use regular expressions and wordlist in file. but i'm not sure about performance

**Comment by AdVetter** [comment]
Teeworlds provides already a "find" function: https://github.com/XXLTomate/XXLDDRace/blob/master/src/base/system.c#L1700
But I dislike the idea of censoring the chat...
