### ISSUE TITLE
sometimes /r doesn't help

### ISSUE THREAD

**Issue by disarmer** [AdVetter/XXLDDRace#7]
sometimes happens that /rescue returns tee in same freeze tile
i fixed it by adding 4 new conditions in method HandleRescue:
# /src/game/server/entities/character.cpp

void CCharacter::HandleRescue()
{   // Nearly the same like IsGrounded(), but with less tolerance
    if ((GameServer()->Collision()->CheckPoint(m_Pos.x+m_ProximityRadius/2, m_Pos.y+m_ProximityRadius/2+1) || GameServer()->Collision()->CheckPoint(m_Pos.x-m_ProximityRadius/2, m_Pos.y+m_ProximityRadius/2+1))
            && m_TileIndex != TILE_FREEZE
            && m_TileFIndex != TILE_FREEZE
            && m_TileIndexL != TILE_FREEZE                        //that
            && m_TileFIndexL != TILE_FREEZE                      //
            && m_TileIndexR != TILE_FREEZE                        //
            && m_TileFIndexR != TILE_FREEZE                      //
            && !m_FreezeTime
            && !m_DeepFreeze
            && !m_LastRescueSave)
    {
        m_RescuePos = m_Pos;
        m_LastRescueSave = 7; // not every point will be stored
    }

}

**Comment by AdVetter** [comment]
Hey disarmer, 
the bug appears, if a tee walks slowly into a freeze tile.

Your patch will solve this bug but will create a new one:
if you have something like this:

X = freeze
_ = ground

XXX_XXX

no checkpoint will be saved on the non freeze tile.
The check has to be more precise.

But thank you for the bug report and patch, I will try to fix it soon :-)

XXLTomate

**Comment by disarmer** [comment]
thanks, yes, it's just workaround.
i think no checkpoint is better than tee will be freezed.
it happens enough often

**Comment by disarmer** [comment]
seems like not fixed, i recompiled and restarted server, but bug still sometimes appears.=(
it behaves as before.
screenshot with debug: http://disarmer.ru/tmp/bug.png

**Comment by AdVetter** [comment]
I tested it now for 10 minutes, but could not reproduce this bug.
It would be nice, if you can test it on my testserver "XXLTESTSERVER" 
and/or contact me in IRC at Kottnet.net/#XXLDDRace

**Comment by disarmer** [comment]
yes, it fixed.
Thank you very much =)
